name: paypadi

description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^10.0.1
  flutter_svg: ^2.0.10+1
  pin_code_text_field: ^1.8.0
  icons_plus: ^5.0.0
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0
  retrofit: ^4.4.2
  talker_dio_logger: ^4.9.1
  talker_flutter: ^4.9.1
  talker_riverpod_logger: ^4.9.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  fpdart: ^1.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.3
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  auto_route_generator: ^10.0.1
  riverpod_generator: ^2.6.5
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter_gen:
  output: lib/config/gen/
  assets:
    outputs:
      class_name: AppAssets
      directory_path_enabled: true

  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/colors.xml

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
